// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Remote command type from iOS system.
enum PlatformRemoteCommand {
  togglePlayPause,
  play,
  pause,
  nextTrack,
  previousTrack,
  skipForward,
  skipBackward,
  changePlaybackPosition,
}

/// Handle referencing a native AudioKit node.
class PlatformNodeHandle {
  PlatformNodeHandle({
    required this.nodeId,
    required this.nodeType,
  });

  String nodeId;

  String nodeType;

  Object encode() {
    return <Object?>[
      nodeId,
      nodeType,
    ];
  }

  static PlatformNodeHandle decode(Object result) {
    result as List<Object?>;
    return PlatformNodeHandle(
      nodeId: result[0]! as String,
      nodeType: result[1]! as String,
    );
  }
}

/// Audio file metadata.
class PlatformAudioFileInfo {
  PlatformAudioFileInfo({
    required this.duration,
    required this.sampleRate,
    required this.channels,
  });

  double duration;

  double sampleRate;

  int channels;

  Object encode() {
    return <Object?>[
      duration,
      sampleRate,
      channels,
    ];
  }

  static PlatformAudioFileInfo decode(Object result) {
    result as List<Object?>;
    return PlatformAudioFileInfo(
      duration: result[0]! as double,
      sampleRate: result[1]! as double,
      channels: result[2]! as int,
    );
  }
}

/// Playback state snapshot.
class PlatformPlaybackState {
  PlatformPlaybackState({
    required this.nodeId,
    required this.statusIndex,
    required this.currentTime,
    required this.duration,
  });

  String nodeId;

  /// Index into PlaybackStatus enum: 0=stopped, 1=playing, 2=paused, 3=scheduling.
  int statusIndex;

  double currentTime;

  double duration;

  Object encode() {
    return <Object?>[
      nodeId,
      statusIndex,
      currentTime,
      duration,
    ];
  }

  static PlatformPlaybackState decode(Object result) {
    result as List<Object?>;
    return PlatformPlaybackState(
      nodeId: result[0]! as String,
      statusIndex: result[1]! as int,
      currentTime: result[2]! as double,
      duration: result[3]! as double,
    );
  }
}

/// Audio level data from AmplitudeTap.
class PlatformAudioLevelData {
  PlatformAudioLevelData({
    required this.nodeId,
    required this.amplitude,
    required this.leftAmplitude,
    required this.rightAmplitude,
  });

  String nodeId;

  double amplitude;

  double leftAmplitude;

  double rightAmplitude;

  Object encode() {
    return <Object?>[
      nodeId,
      amplitude,
      leftAmplitude,
      rightAmplitude,
    ];
  }

  static PlatformAudioLevelData decode(Object result) {
    result as List<Object?>;
    return PlatformAudioLevelData(
      nodeId: result[0]! as String,
      amplitude: result[1]! as double,
      leftAmplitude: result[2]! as double,
      rightAmplitude: result[3]! as double,
    );
  }
}

/// Pitch detection data from PitchTap.
class PlatformPitchData {
  PlatformPitchData({
    required this.nodeId,
    required this.leftPitch,
    required this.rightPitch,
    required this.leftAmplitude,
    required this.rightAmplitude,
  });

  String nodeId;

  double leftPitch;

  double rightPitch;

  double leftAmplitude;

  double rightAmplitude;

  Object encode() {
    return <Object?>[
      nodeId,
      leftPitch,
      rightPitch,
      leftAmplitude,
      rightAmplitude,
    ];
  }

  static PlatformPitchData decode(Object result) {
    result as List<Object?>;
    return PlatformPitchData(
      nodeId: result[0]! as String,
      leftPitch: result[1]! as double,
      rightPitch: result[2]! as double,
      leftAmplitude: result[3]! as double,
      rightAmplitude: result[4]! as double,
    );
  }
}

/// Node parameter info.
class PlatformNodeParameterInfo {
  PlatformNodeParameterInfo({
    required this.identifier,
    required this.name,
    required this.value,
    required this.defaultValue,
    required this.minValue,
    required this.maxValue,
  });

  String identifier;

  String name;

  double value;

  double defaultValue;

  double minValue;

  double maxValue;

  Object encode() {
    return <Object?>[
      identifier,
      name,
      value,
      defaultValue,
      minValue,
      maxValue,
    ];
  }

  static PlatformNodeParameterInfo decode(Object result) {
    result as List<Object?>;
    return PlatformNodeParameterInfo(
      identifier: result[0]! as String,
      name: result[1]! as String,
      value: result[2]! as double,
      defaultValue: result[3]! as double,
      minValue: result[4]! as double,
      maxValue: result[5]! as double,
    );
  }
}

/// Metadata for iOS Now Playing Info Center.
class PlatformNowPlayingInfo {
  PlatformNowPlayingInfo({
    required this.title,
    required this.artist,
    this.artworkAssetKey,
    required this.isPlaying,
    this.duration,
    this.currentTime,
    required this.isLiveStream,
  });

  String title;

  String artist;

  String? artworkAssetKey;

  bool isPlaying;

  double? duration;

  double? currentTime;

  bool isLiveStream;

  Object encode() {
    return <Object?>[
      title,
      artist,
      artworkAssetKey,
      isPlaying,
      duration,
      currentTime,
      isLiveStream,
    ];
  }

  static PlatformNowPlayingInfo decode(Object result) {
    result as List<Object?>;
    return PlatformNowPlayingInfo(
      title: result[0]! as String,
      artist: result[1]! as String,
      artworkAssetKey: result[2] as String?,
      isPlaying: result[3]! as bool,
      duration: result[4] as double?,
      currentTime: result[5] as double?,
      isLiveStream: result[6]! as bool,
    );
  }
}

/// Configuration for which remote commands are enabled.
class PlatformRemoteCommandConfig {
  PlatformRemoteCommandConfig({
    required this.playPauseEnabled,
    required this.nextTrackEnabled,
    required this.previousTrackEnabled,
    required this.skipForwardEnabled,
    required this.skipForwardInterval,
    required this.skipBackwardEnabled,
    required this.skipBackwardInterval,
    required this.seekEnabled,
  });

  bool playPauseEnabled;

  bool nextTrackEnabled;

  bool previousTrackEnabled;

  bool skipForwardEnabled;

  double skipForwardInterval;

  bool skipBackwardEnabled;

  double skipBackwardInterval;

  bool seekEnabled;

  Object encode() {
    return <Object?>[
      playPauseEnabled,
      nextTrackEnabled,
      previousTrackEnabled,
      skipForwardEnabled,
      skipForwardInterval,
      skipBackwardEnabled,
      skipBackwardInterval,
      seekEnabled,
    ];
  }

  static PlatformRemoteCommandConfig decode(Object result) {
    result as List<Object?>;
    return PlatformRemoteCommandConfig(
      playPauseEnabled: result[0]! as bool,
      nextTrackEnabled: result[1]! as bool,
      previousTrackEnabled: result[2]! as bool,
      skipForwardEnabled: result[3]! as bool,
      skipForwardInterval: result[4]! as double,
      skipBackwardEnabled: result[5]! as bool,
      skipBackwardInterval: result[6]! as double,
      seekEnabled: result[7]! as bool,
    );
  }
}

/// Remote command event with optional position data.
class PlatformRemoteCommandEvent {
  PlatformRemoteCommandEvent({
    required this.command,
    this.position,
  });

  PlatformRemoteCommand command;

  double? position;

  Object encode() {
    return <Object?>[
      command,
      position,
    ];
  }

  static PlatformRemoteCommandEvent decode(Object result) {
    result as List<Object?>;
    return PlatformRemoteCommandEvent(
      command: result[0]! as PlatformRemoteCommand,
      position: result[1] as double?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformRemoteCommand) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformNodeHandle) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformAudioFileInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformPlaybackState) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformAudioLevelData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformPitchData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformNodeParameterInfo) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformNowPlayingInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformRemoteCommandConfig) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformRemoteCommandEvent) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformRemoteCommand.values[value];
      case 130: 
        return PlatformNodeHandle.decode(readValue(buffer)!);
      case 131: 
        return PlatformAudioFileInfo.decode(readValue(buffer)!);
      case 132: 
        return PlatformPlaybackState.decode(readValue(buffer)!);
      case 133: 
        return PlatformAudioLevelData.decode(readValue(buffer)!);
      case 134: 
        return PlatformPitchData.decode(readValue(buffer)!);
      case 135: 
        return PlatformNodeParameterInfo.decode(readValue(buffer)!);
      case 136: 
        return PlatformNowPlayingInfo.decode(readValue(buffer)!);
      case 137: 
        return PlatformRemoteCommandConfig.decode(readValue(buffer)!);
      case 138: 
        return PlatformRemoteCommandEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AudioKitHostApi {
  /// Constructor for [AudioKitHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AudioKitHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> createEngine() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> startEngine(String engineId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[engineId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopEngine(String engineId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[engineId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> pauseEngine(String engineId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.pauseEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[engineId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setEngineOutput(String engineId, String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setEngineOutput$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[engineId, nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disposeEngine(String engineId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.disposeEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[engineId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PlatformNodeHandle> createAudioPlayer() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createAudioPlayer$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformNodeHandle?)!;
    }
  }

  Future<PlatformAudioFileInfo> loadAudioFile(String nodeId, String filePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.loadAudioFile$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, filePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformAudioFileInfo?)!;
    }
  }

  Future<void> playerPlay(String nodeId, double? startTime, double? endTime) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerPlay$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, startTime, endTime]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> playerPause(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerPause$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> playerResume(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerResume$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> playerStop(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerStop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> playerSeek(String nodeId, double time) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerSeek$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, time]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPlayerVolume(String nodeId, double volume) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setPlayerVolume$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, volume]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPlayerIsLooping(String nodeId, bool isLooping) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setPlayerIsLooping$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, isLooping]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPlayerIsReversed(String nodeId, bool isReversed) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setPlayerIsReversed$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, isReversed]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PlatformPlaybackState> getPlayerState(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.getPlayerState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformPlaybackState?)!;
    }
  }

  Future<PlatformNodeHandle> createMixer(List<String> inputNodeIds, double volume, String? name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createMixer$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[inputNodeIds, volume, name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformNodeHandle?)!;
    }
  }

  Future<void> mixerAddInput(String mixerId, String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.mixerAddInput$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mixerId, nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> mixerRemoveInput(String mixerId, String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.mixerRemoveInput$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mixerId, nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> mixerRemoveAllInputs(String mixerId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.mixerRemoveAllInputs$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mixerId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setMixerVolume(String mixerId, double volume) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setMixerVolume$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mixerId, volume]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setMixerPan(String mixerId, double pan) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setMixerPan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mixerId, pan]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setMixerName(String mixerId, String name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setMixerName$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mixerId, name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PlatformNodeHandle> createTimePitch(String inputNodeId, double rate, double pitch, double overlap) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createTimePitch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[inputNodeId, rate, pitch, overlap]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformNodeHandle?)!;
    }
  }

  Future<void> setTimePitchRate(String nodeId, double rate) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setTimePitchRate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, rate]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setTimePitchPitch(String nodeId, double pitch) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setTimePitchPitch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, pitch]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setTimePitchOverlap(String nodeId, double overlap) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setTimePitchOverlap$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, overlap]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PlatformNodeHandle> createVariSpeed(String inputNodeId, double rate) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createVariSpeed$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[inputNodeId, rate]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformNodeHandle?)!;
    }
  }

  Future<void> setVariSpeedRate(String nodeId, double rate) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setVariSpeedRate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, rate]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startNode(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startNode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopNode(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopNode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> bypassNode(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.bypassNode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disposeNode(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.disposeNode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isNodeStarted(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.isNodeStarted$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<List<PlatformNodeParameterInfo>> getNodeParameters(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.getNodeParameters$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<PlatformNodeParameterInfo>();
    }
  }

  Future<void> setNodeParameter(String nodeId, String identifier, double value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setNodeParameter$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, identifier, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> rampNodeParameter(String nodeId, String identifier, double value, double duration, double delay) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.rampNodeParameter$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, identifier, value, duration, delay]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PlatformNodeHandle> createOscillator(double frequency, double amplitude) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createOscillator$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[frequency, amplitude]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformNodeHandle?)!;
    }
  }

  Future<PlatformNodeHandle> createEffect(String inputNodeId, String effectType, Map<String, double> params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createEffect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[inputNodeId, effectType, params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformNodeHandle?)!;
    }
  }

  Future<void> loadReverbPreset(String nodeId, int presetIndex) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.loadReverbPreset$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, presetIndex]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Creates a Convolution effect node with an impulse response file.
  Future<PlatformNodeHandle> createConvolution(String inputNodeId, String impulseResponseFilePath, int partitionLength) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createConvolution$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[inputNodeId, impulseResponseFilePath, partitionLength]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformNodeHandle?)!;
    }
  }

  Future<void> startAmplitudeTap(String nodeId, int bufferSize) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startAmplitudeTap$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, bufferSize]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopAmplitudeTap(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopAmplitudeTap$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startPitchTap(String nodeId, int bufferSize) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startPitchTap$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId, bufferSize]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopPitchTap(String nodeId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopPitchTap$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nodeId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setGlobalSampleRate(double sampleRate) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setGlobalSampleRate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[sampleRate]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setGlobalBufferLength(int bufferLengthPower) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setGlobalBufferLength$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[bufferLengthPower]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setLogLevel(int level) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setLogLevel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[level]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateNowPlayingInfo(PlatformNowPlayingInfo info) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.updateNowPlayingInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[info]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> clearNowPlayingInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.clearNowPlayingInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> configureRemoteCommands(PlatformRemoteCommandConfig config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.configureRemoteCommands$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disableRemoteCommands() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.disableRemoteCommands$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class AudioKitFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPlaybackStateChanged(PlatformPlaybackState state);

  void onPlaybackCompleted(String nodeId);

  void onAmplitudeData(PlatformAudioLevelData data);

  void onError(String nodeId, String code, String message);

  void onPitchData(PlatformPitchData data);

  void onRemoteCommand(PlatformRemoteCommandEvent event);

  static void setUp(AudioKitFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformPlaybackState? arg_state = (args[0] as PlatformPlaybackState?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackStateChanged was null, expected non-null PlatformPlaybackState.');
          try {
            api.onPlaybackStateChanged(arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackCompleted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackCompleted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_nodeId = (args[0] as String?);
          assert(arg_nodeId != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackCompleted was null, expected non-null String.');
          try {
            api.onPlaybackCompleted(arg_nodeId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onAmplitudeData$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onAmplitudeData was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformAudioLevelData? arg_data = (args[0] as PlatformAudioLevelData?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onAmplitudeData was null, expected non-null PlatformAudioLevelData.');
          try {
            api.onAmplitudeData(arg_data!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_nodeId = (args[0] as String?);
          assert(arg_nodeId != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onError was null, expected non-null String.');
          final String? arg_code = (args[1] as String?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onError was null, expected non-null String.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_nodeId!, arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPitchData$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPitchData was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformPitchData? arg_data = (args[0] as PlatformPitchData?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPitchData was null, expected non-null PlatformPitchData.');
          try {
            api.onPitchData(arg_data!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onRemoteCommand$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onRemoteCommand was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformRemoteCommandEvent? arg_event = (args[0] as PlatformRemoteCommandEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onRemoteCommand was null, expected non-null PlatformRemoteCommandEvent.');
          try {
            api.onRemoteCommand(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
