name: flutter_audiokit_platform_interface
description: A common platform interface for the flutter_audiokit plugin.
version: 0.1.0
homepage: https://github.com/user/flutter_audiokit

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
