// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Handle referencing a native AudioKit node.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformNodeHandle {
  var nodeId: String
  var nodeType: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformNodeHandle? {
    let nodeId = pigeonVar_list[0] as! String
    let nodeType = pigeonVar_list[1] as! String

    return PlatformNodeHandle(
      nodeId: nodeId,
      nodeType: nodeType
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      nodeType,
    ]
  }
}

/// Audio file metadata.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAudioFileInfo {
  var duration: Double
  var sampleRate: Double
  var channels: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAudioFileInfo? {
    let duration = pigeonVar_list[0] as! Double
    let sampleRate = pigeonVar_list[1] as! Double
    let channels = pigeonVar_list[2] as! Int64

    return PlatformAudioFileInfo(
      duration: duration,
      sampleRate: sampleRate,
      channels: channels
    )
  }
  func toList() -> [Any?] {
    return [
      duration,
      sampleRate,
      channels,
    ]
  }
}

/// Playback state snapshot.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPlaybackState {
  var nodeId: String
  /// Index into PlaybackStatus enum: 0=stopped, 1=playing, 2=paused, 3=scheduling.
  var statusIndex: Int64
  var currentTime: Double
  var duration: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPlaybackState? {
    let nodeId = pigeonVar_list[0] as! String
    let statusIndex = pigeonVar_list[1] as! Int64
    let currentTime = pigeonVar_list[2] as! Double
    let duration = pigeonVar_list[3] as! Double

    return PlatformPlaybackState(
      nodeId: nodeId,
      statusIndex: statusIndex,
      currentTime: currentTime,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      statusIndex,
      currentTime,
      duration,
    ]
  }
}

/// Audio level data from AmplitudeTap.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAudioLevelData {
  var nodeId: String
  var amplitude: Double
  var leftAmplitude: Double
  var rightAmplitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAudioLevelData? {
    let nodeId = pigeonVar_list[0] as! String
    let amplitude = pigeonVar_list[1] as! Double
    let leftAmplitude = pigeonVar_list[2] as! Double
    let rightAmplitude = pigeonVar_list[3] as! Double

    return PlatformAudioLevelData(
      nodeId: nodeId,
      amplitude: amplitude,
      leftAmplitude: leftAmplitude,
      rightAmplitude: rightAmplitude
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      amplitude,
      leftAmplitude,
      rightAmplitude,
    ]
  }
}

/// Pitch detection data from PitchTap.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPitchData {
  var nodeId: String
  var leftPitch: Double
  var rightPitch: Double
  var leftAmplitude: Double
  var rightAmplitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPitchData? {
    let nodeId = pigeonVar_list[0] as! String
    let leftPitch = pigeonVar_list[1] as! Double
    let rightPitch = pigeonVar_list[2] as! Double
    let leftAmplitude = pigeonVar_list[3] as! Double
    let rightAmplitude = pigeonVar_list[4] as! Double

    return PlatformPitchData(
      nodeId: nodeId,
      leftPitch: leftPitch,
      rightPitch: rightPitch,
      leftAmplitude: leftAmplitude,
      rightAmplitude: rightAmplitude
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      leftPitch,
      rightPitch,
      leftAmplitude,
      rightAmplitude,
    ]
  }
}

/// Node parameter info.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformNodeParameterInfo {
  var identifier: String
  var name: String
  var value: Double
  var defaultValue: Double
  var minValue: Double
  var maxValue: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformNodeParameterInfo? {
    let identifier = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let value = pigeonVar_list[2] as! Double
    let defaultValue = pigeonVar_list[3] as! Double
    let minValue = pigeonVar_list[4] as! Double
    let maxValue = pigeonVar_list[5] as! Double

    return PlatformNodeParameterInfo(
      identifier: identifier,
      name: name,
      value: value,
      defaultValue: defaultValue,
      minValue: minValue,
      maxValue: maxValue
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      name,
      value,
      defaultValue,
      minValue,
      maxValue,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PlatformNodeHandle.fromList(self.readValue() as! [Any?])
    case 130:
      return PlatformAudioFileInfo.fromList(self.readValue() as! [Any?])
    case 131:
      return PlatformPlaybackState.fromList(self.readValue() as! [Any?])
    case 132:
      return PlatformAudioLevelData.fromList(self.readValue() as! [Any?])
    case 133:
      return PlatformPitchData.fromList(self.readValue() as! [Any?])
    case 134:
      return PlatformNodeParameterInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformNodeHandle {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAudioFileInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPlaybackState {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAudioLevelData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPitchData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformNodeParameterInfo {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioKitHostApi {
  func createEngine(completion: @escaping (Result<String, Error>) -> Void)
  func startEngine(engineId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func stopEngine(engineId: String) throws
  func pauseEngine(engineId: String) throws
  func setEngineOutput(engineId: String, nodeId: String) throws
  func disposeEngine(engineId: String) throws
  func createAudioPlayer(completion: @escaping (Result<PlatformNodeHandle, Error>) -> Void)
  func loadAudioFile(nodeId: String, filePath: String, completion: @escaping (Result<PlatformAudioFileInfo, Error>) -> Void)
  func playerPlay(nodeId: String, startTime: Double?, endTime: Double?) throws
  func playerPause(nodeId: String) throws
  func playerResume(nodeId: String) throws
  func playerStop(nodeId: String) throws
  func playerSeek(nodeId: String, time: Double) throws
  func setPlayerVolume(nodeId: String, volume: Double) throws
  func setPlayerIsLooping(nodeId: String, isLooping: Bool) throws
  func setPlayerIsReversed(nodeId: String, isReversed: Bool) throws
  func getPlayerState(nodeId: String, completion: @escaping (Result<PlatformPlaybackState, Error>) -> Void)
  func createMixer(inputNodeIds: [String], volume: Double, name: String?) throws -> PlatformNodeHandle
  func mixerAddInput(mixerId: String, nodeId: String) throws
  func mixerRemoveInput(mixerId: String, nodeId: String) throws
  func mixerRemoveAllInputs(mixerId: String) throws
  func setMixerVolume(mixerId: String, volume: Double) throws
  func setMixerPan(mixerId: String, pan: Double) throws
  func setMixerName(mixerId: String, name: String) throws
  func createTimePitch(inputNodeId: String, rate: Double, pitch: Double, overlap: Double) throws -> PlatformNodeHandle
  func setTimePitchRate(nodeId: String, rate: Double) throws
  func setTimePitchPitch(nodeId: String, pitch: Double) throws
  func setTimePitchOverlap(nodeId: String, overlap: Double) throws
  func createVariSpeed(inputNodeId: String, rate: Double) throws -> PlatformNodeHandle
  func setVariSpeedRate(nodeId: String, rate: Double) throws
  func startNode(nodeId: String) throws
  func stopNode(nodeId: String) throws
  func bypassNode(nodeId: String) throws
  func disposeNode(nodeId: String) throws
  func isNodeStarted(nodeId: String) throws -> Bool
  func getNodeParameters(nodeId: String) throws -> [PlatformNodeParameterInfo]
  func setNodeParameter(nodeId: String, identifier: String, value: Double) throws
  func rampNodeParameter(nodeId: String, identifier: String, value: Double, duration: Double, delay: Double) throws
  func createOscillator(frequency: Double, amplitude: Double) throws -> PlatformNodeHandle
  func createEffect(inputNodeId: String, effectType: String, params: [String: Double]) throws -> PlatformNodeHandle
  func loadReverbPreset(nodeId: String, presetIndex: Int64) throws
  /// Creates a Convolution effect node with an impulse response file.
  func createConvolution(inputNodeId: String, impulseResponseFilePath: String, partitionLength: Int64) throws -> PlatformNodeHandle
  func startAmplitudeTap(nodeId: String, bufferSize: Int64) throws
  func stopAmplitudeTap(nodeId: String) throws
  func startPitchTap(nodeId: String, bufferSize: Int64) throws
  func stopPitchTap(nodeId: String) throws
  func setGlobalSampleRate(sampleRate: Double) throws
  func setGlobalBufferLength(bufferLengthPower: Int64) throws
  func setLogLevel(level: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioKitHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AudioKitHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioKitHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createEngineChannel.setMessageHandler { _, reply in
        api.createEngine { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createEngineChannel.setMessageHandler(nil)
    }
    let startEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startEngineChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let engineIdArg = args[0] as! String
        api.startEngine(engineId: engineIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startEngineChannel.setMessageHandler(nil)
    }
    let stopEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopEngineChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let engineIdArg = args[0] as! String
        do {
          try api.stopEngine(engineId: engineIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopEngineChannel.setMessageHandler(nil)
    }
    let pauseEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.pauseEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseEngineChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let engineIdArg = args[0] as! String
        do {
          try api.pauseEngine(engineId: engineIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseEngineChannel.setMessageHandler(nil)
    }
    let setEngineOutputChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setEngineOutput\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setEngineOutputChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let engineIdArg = args[0] as! String
        let nodeIdArg = args[1] as! String
        do {
          try api.setEngineOutput(engineId: engineIdArg, nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setEngineOutputChannel.setMessageHandler(nil)
    }
    let disposeEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.disposeEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeEngineChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let engineIdArg = args[0] as! String
        do {
          try api.disposeEngine(engineId: engineIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeEngineChannel.setMessageHandler(nil)
    }
    let createAudioPlayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createAudioPlayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createAudioPlayerChannel.setMessageHandler { _, reply in
        api.createAudioPlayer { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createAudioPlayerChannel.setMessageHandler(nil)
    }
    let loadAudioFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.loadAudioFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadAudioFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let filePathArg = args[1] as! String
        api.loadAudioFile(nodeId: nodeIdArg, filePath: filePathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadAudioFileChannel.setMessageHandler(nil)
    }
    let playerPlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerPlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playerPlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let startTimeArg: Double? = nilOrValue(args[1])
        let endTimeArg: Double? = nilOrValue(args[2])
        do {
          try api.playerPlay(nodeId: nodeIdArg, startTime: startTimeArg, endTime: endTimeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playerPlayChannel.setMessageHandler(nil)
    }
    let playerPauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerPause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playerPauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.playerPause(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playerPauseChannel.setMessageHandler(nil)
    }
    let playerResumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerResume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playerResumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.playerResume(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playerResumeChannel.setMessageHandler(nil)
    }
    let playerStopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerStop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playerStopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.playerStop(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playerStopChannel.setMessageHandler(nil)
    }
    let playerSeekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.playerSeek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playerSeekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let timeArg = args[1] as! Double
        do {
          try api.playerSeek(nodeId: nodeIdArg, time: timeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playerSeekChannel.setMessageHandler(nil)
    }
    let setPlayerVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setPlayerVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPlayerVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let volumeArg = args[1] as! Double
        do {
          try api.setPlayerVolume(nodeId: nodeIdArg, volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPlayerVolumeChannel.setMessageHandler(nil)
    }
    let setPlayerIsLoopingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setPlayerIsLooping\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPlayerIsLoopingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let isLoopingArg = args[1] as! Bool
        do {
          try api.setPlayerIsLooping(nodeId: nodeIdArg, isLooping: isLoopingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPlayerIsLoopingChannel.setMessageHandler(nil)
    }
    let setPlayerIsReversedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setPlayerIsReversed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPlayerIsReversedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let isReversedArg = args[1] as! Bool
        do {
          try api.setPlayerIsReversed(nodeId: nodeIdArg, isReversed: isReversedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPlayerIsReversedChannel.setMessageHandler(nil)
    }
    let getPlayerStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.getPlayerState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlayerStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        api.getPlayerState(nodeId: nodeIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPlayerStateChannel.setMessageHandler(nil)
    }
    let createMixerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createMixer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createMixerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputNodeIdsArg = args[0] as! [String]
        let volumeArg = args[1] as! Double
        let nameArg: String? = nilOrValue(args[2])
        do {
          let result = try api.createMixer(inputNodeIds: inputNodeIdsArg, volume: volumeArg, name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createMixerChannel.setMessageHandler(nil)
    }
    let mixerAddInputChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.mixerAddInput\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mixerAddInputChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mixerIdArg = args[0] as! String
        let nodeIdArg = args[1] as! String
        do {
          try api.mixerAddInput(mixerId: mixerIdArg, nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      mixerAddInputChannel.setMessageHandler(nil)
    }
    let mixerRemoveInputChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.mixerRemoveInput\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mixerRemoveInputChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mixerIdArg = args[0] as! String
        let nodeIdArg = args[1] as! String
        do {
          try api.mixerRemoveInput(mixerId: mixerIdArg, nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      mixerRemoveInputChannel.setMessageHandler(nil)
    }
    let mixerRemoveAllInputsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.mixerRemoveAllInputs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mixerRemoveAllInputsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mixerIdArg = args[0] as! String
        do {
          try api.mixerRemoveAllInputs(mixerId: mixerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      mixerRemoveAllInputsChannel.setMessageHandler(nil)
    }
    let setMixerVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setMixerVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMixerVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mixerIdArg = args[0] as! String
        let volumeArg = args[1] as! Double
        do {
          try api.setMixerVolume(mixerId: mixerIdArg, volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMixerVolumeChannel.setMessageHandler(nil)
    }
    let setMixerPanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setMixerPan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMixerPanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mixerIdArg = args[0] as! String
        let panArg = args[1] as! Double
        do {
          try api.setMixerPan(mixerId: mixerIdArg, pan: panArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMixerPanChannel.setMessageHandler(nil)
    }
    let setMixerNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setMixerName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMixerNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mixerIdArg = args[0] as! String
        let nameArg = args[1] as! String
        do {
          try api.setMixerName(mixerId: mixerIdArg, name: nameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMixerNameChannel.setMessageHandler(nil)
    }
    let createTimePitchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createTimePitch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createTimePitchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputNodeIdArg = args[0] as! String
        let rateArg = args[1] as! Double
        let pitchArg = args[2] as! Double
        let overlapArg = args[3] as! Double
        do {
          let result = try api.createTimePitch(inputNodeId: inputNodeIdArg, rate: rateArg, pitch: pitchArg, overlap: overlapArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createTimePitchChannel.setMessageHandler(nil)
    }
    let setTimePitchRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setTimePitchRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTimePitchRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let rateArg = args[1] as! Double
        do {
          try api.setTimePitchRate(nodeId: nodeIdArg, rate: rateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTimePitchRateChannel.setMessageHandler(nil)
    }
    let setTimePitchPitchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setTimePitchPitch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTimePitchPitchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let pitchArg = args[1] as! Double
        do {
          try api.setTimePitchPitch(nodeId: nodeIdArg, pitch: pitchArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTimePitchPitchChannel.setMessageHandler(nil)
    }
    let setTimePitchOverlapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setTimePitchOverlap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTimePitchOverlapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let overlapArg = args[1] as! Double
        do {
          try api.setTimePitchOverlap(nodeId: nodeIdArg, overlap: overlapArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTimePitchOverlapChannel.setMessageHandler(nil)
    }
    let createVariSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createVariSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createVariSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputNodeIdArg = args[0] as! String
        let rateArg = args[1] as! Double
        do {
          let result = try api.createVariSpeed(inputNodeId: inputNodeIdArg, rate: rateArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createVariSpeedChannel.setMessageHandler(nil)
    }
    let setVariSpeedRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setVariSpeedRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVariSpeedRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let rateArg = args[1] as! Double
        do {
          try api.setVariSpeedRate(nodeId: nodeIdArg, rate: rateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVariSpeedRateChannel.setMessageHandler(nil)
    }
    let startNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.startNode(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startNodeChannel.setMessageHandler(nil)
    }
    let stopNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.stopNode(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopNodeChannel.setMessageHandler(nil)
    }
    let bypassNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.bypassNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bypassNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.bypassNode(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      bypassNodeChannel.setMessageHandler(nil)
    }
    let disposeNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.disposeNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.disposeNode(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeNodeChannel.setMessageHandler(nil)
    }
    let isNodeStartedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.isNodeStarted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isNodeStartedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          let result = try api.isNodeStarted(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isNodeStartedChannel.setMessageHandler(nil)
    }
    let getNodeParametersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.getNodeParameters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNodeParametersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          let result = try api.getNodeParameters(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNodeParametersChannel.setMessageHandler(nil)
    }
    let setNodeParameterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setNodeParameter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNodeParameterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let identifierArg = args[1] as! String
        let valueArg = args[2] as! Double
        do {
          try api.setNodeParameter(nodeId: nodeIdArg, identifier: identifierArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNodeParameterChannel.setMessageHandler(nil)
    }
    let rampNodeParameterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.rampNodeParameter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rampNodeParameterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let identifierArg = args[1] as! String
        let valueArg = args[2] as! Double
        let durationArg = args[3] as! Double
        let delayArg = args[4] as! Double
        do {
          try api.rampNodeParameter(nodeId: nodeIdArg, identifier: identifierArg, value: valueArg, duration: durationArg, delay: delayArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rampNodeParameterChannel.setMessageHandler(nil)
    }
    let createOscillatorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createOscillator\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createOscillatorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let frequencyArg = args[0] as! Double
        let amplitudeArg = args[1] as! Double
        do {
          let result = try api.createOscillator(frequency: frequencyArg, amplitude: amplitudeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createOscillatorChannel.setMessageHandler(nil)
    }
    let createEffectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createEffect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createEffectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputNodeIdArg = args[0] as! String
        let effectTypeArg = args[1] as! String
        let paramsArg = args[2] as! [String: Double]
        do {
          let result = try api.createEffect(inputNodeId: inputNodeIdArg, effectType: effectTypeArg, params: paramsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createEffectChannel.setMessageHandler(nil)
    }
    let loadReverbPresetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.loadReverbPreset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadReverbPresetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let presetIndexArg = args[1] as! Int64
        do {
          try api.loadReverbPreset(nodeId: nodeIdArg, presetIndex: presetIndexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadReverbPresetChannel.setMessageHandler(nil)
    }
    /// Creates a Convolution effect node with an impulse response file.
    let createConvolutionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.createConvolution\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createConvolutionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputNodeIdArg = args[0] as! String
        let impulseResponseFilePathArg = args[1] as! String
        let partitionLengthArg = args[2] as! Int64
        do {
          let result = try api.createConvolution(inputNodeId: inputNodeIdArg, impulseResponseFilePath: impulseResponseFilePathArg, partitionLength: partitionLengthArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createConvolutionChannel.setMessageHandler(nil)
    }
    let startAmplitudeTapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startAmplitudeTap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAmplitudeTapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let bufferSizeArg = args[1] as! Int64
        do {
          try api.startAmplitudeTap(nodeId: nodeIdArg, bufferSize: bufferSizeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAmplitudeTapChannel.setMessageHandler(nil)
    }
    let stopAmplitudeTapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopAmplitudeTap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAmplitudeTapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.stopAmplitudeTap(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopAmplitudeTapChannel.setMessageHandler(nil)
    }
    let startPitchTapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.startPitchTap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startPitchTapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let bufferSizeArg = args[1] as! Int64
        do {
          try api.startPitchTap(nodeId: nodeIdArg, bufferSize: bufferSizeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startPitchTapChannel.setMessageHandler(nil)
    }
    let stopPitchTapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.stopPitchTap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopPitchTapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        do {
          try api.stopPitchTap(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopPitchTapChannel.setMessageHandler(nil)
    }
    let setGlobalSampleRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setGlobalSampleRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setGlobalSampleRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sampleRateArg = args[0] as! Double
        do {
          try api.setGlobalSampleRate(sampleRate: sampleRateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setGlobalSampleRateChannel.setMessageHandler(nil)
    }
    let setGlobalBufferLengthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setGlobalBufferLength\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setGlobalBufferLengthChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bufferLengthPowerArg = args[0] as! Int64
        do {
          try api.setGlobalBufferLength(bufferLengthPower: bufferLengthPowerArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setGlobalBufferLengthChannel.setMessageHandler(nil)
    }
    let setLogLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitHostApi.setLogLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! Int64
        do {
          try api.setLogLevel(level: levelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLogLevelChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AudioKitFlutterApiProtocol {
  func onPlaybackStateChanged(state stateArg: PlatformPlaybackState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPlaybackCompleted(nodeId nodeIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAmplitudeData(data dataArg: PlatformAudioLevelData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(nodeId nodeIdArg: String, code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPitchData(data dataArg: PlatformPitchData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AudioKitFlutterApi: AudioKitFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onPlaybackStateChanged(state stateArg: PlatformPlaybackState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPlaybackCompleted(nodeId nodeIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPlaybackCompleted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([nodeIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAmplitudeData(data dataArg: PlatformAudioLevelData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onAmplitudeData\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(nodeId nodeIdArg: String, code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([nodeIdArg, codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPitchData(data dataArg: PlatformPitchData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_audiokit_ios.AudioKitFlutterApi.onPitchData\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
